services:
  mysql:
    image: mysql:8.4
    container_name: stockflow-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - stockflow_mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build: .
    container_name: stockflow-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      CONTAINER_PORT: ${CONTAINER_PORT}

      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      # Optional: only needed if your app actually sends emails in dev
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      UI_APP_URL: ${UI_APP_URL}
    ports:
      - "${CONTAINER_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped
  frontend:
    build:
      context: ../warehousestockflowapp
    container_name: stockflow-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  stockflow_mysql_data: